version: '3'

services:

  db-mysql:
    image: mysql:5.6
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=dbcarros
      - MYSQL_PASSWORD=123456
    volumes:
      - volume-data:/var/lib/mysql
    ports:
      - 3306:3306
    networks:
      - networkapi

  api-carros:
    image: api-carros:1
    restart: on-failure
    ports:
      - 8088:8088
    depends_on:
      - db-mysql
    networks:
      - networkapi

networks:
  networkapi:
    driver: bridge

volumes:
  volume-data:
