server:
    port: 8088

spring:
    datasource:
        url: ${MYSQL_URL:jdbc:mysql://db-mysql:3306/dbcarros?createDatabaseIfNotExist=true&autoReconnect=true&useSSL=false}
        username: ${MYSQL_USER}
        password: ${MYSQL_PASSWORD}
        testWhileIdle: true
        validationQuery: SELECT 1

    jpa:
        show-sql: true
        hibernate:
            ddl-auto: update
            naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL5Dialect
