apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-carros
  labels:
    app: api-carros
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-carros
  template:
    metadata:
      labels:
        app: api-carros
    spec:
      containers:
        - name: api-carros
          image: kalatunga/api-carros:1
          imagePullPolicy: IfNotPresent
          command:
            - /bin/bash
            - -ec
            - sleep 30; touch /tmp/ready; sleep 600
          readinessProbe:
            exec:
              command:
                - cat
                - /tmp/ready
            initialDelaySeconds: 10
            periodSeconds: 5
          ports:
            - containerPort: 8088
          env:
            - name: DB_URL
              valueFrom:
                configMapKeyRef:
                  name: mysql-configmap
                  key: database_url
            - name: DB_USER
              valueFrom:
                configMapKeyRef:
                  name: mysql-configmap
                  key: database_user
            - name: DB_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: mysql-configmap
                  key: database_password
      volumes:
        - name: mysql-persistence-storage
          persistentVolumeClaim:
            claimName: db-mysql-pvc
