apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-carros
  labels:
    app: api-carros
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-carros
  template:
    metadata:
      labels:
        app: api-carros
    spec:
      containers:
        - name: api-carros
          image: kalatunga/api-carros:1
          imagePullPolicy: Never
          ports:
            - containerPort: 8088
          env:
            - name: MYSQL_URL
              valueFrom:
                configMapKeyRef:
                  name: mysql-configmap
                  key: database_url
            - name: MSQL_USER
              valueFrom:
                configMapKeyRef:
                  name: mysql-configmap
                  key: database_user
            - name: MYSQL_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: mysql-configmap
                  key: database_password
