apiVersion: v1
kind: Service
metadata:
  name: db-mysql
  labels:
    run: db-mysql
spec:
  ports:
    - port: 3306
      targetPort: 3306
      protocol: TCP
      nodePort: 30003
  type: NodePort
  selector:
    app: db-mysql
